import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Image from "next/image";

const index = () => {
  return (
    <>
      <Head>
        <title>CitiTasker.Com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <center>
        <h3>Welcome to CitiTasker User.name</h3>
      </center>
      <div className="Home">
        <Image
          src="/hero_image.jpg"
          height={700}
          width={1000}
          background
          alt="Hero_image"
          className="hero_image"
        />
      </div>
    </>
  );
};

export default index;
