import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";

const index = () => {
  return (
    <>
      <Head>
        <title>CitiTasker.Com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="Home">Welcome to CitiTasker User.name</div>
    </>
  );
};

export default index;
